// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cpp_tw_gender
IntegerVector cpp_tw_gender(CharacterVector x, CharacterVector male, CharacterVector female);
RcppExport SEXP _twitterreport_cpp_tw_gender(SEXP xSEXP, SEXP maleSEXP, SEXP femaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type male(maleSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type female(femaleSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_tw_gender(x, male, female));
    return rcpp_result_gen;
END_RCPP
}
// cpp_jaccard_coef
arma::sp_mat cpp_jaccard_coef(IntegerVector wrds_id, IntegerVector wrds_grp, bool dist);
RcppExport SEXP _twitterreport_cpp_jaccard_coef(SEXP wrds_idSEXP, SEXP wrds_grpSEXP, SEXP distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type wrds_id(wrds_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type wrds_grp(wrds_grpSEXP);
    Rcpp::traits::input_parameter< bool >::type dist(distSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_jaccard_coef(wrds_id, wrds_grp, dist));
    return rcpp_result_gen;
END_RCPP
}
// cpp_char_list_as_df
DataFrame cpp_char_list_as_df(List& X);
RcppExport SEXP _twitterreport_cpp_char_list_as_df(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_char_list_as_df(X));
    return rcpp_result_gen;
END_RCPP
}
// cpp_tw_sentiment
NumericVector cpp_tw_sentiment(const List x, CharacterVector pos, CharacterVector neg, const NumericVector pos_score, const NumericVector neg_score, CharacterVector neu, const NumericVector neu_score, bool normalize);
RcppExport SEXP _twitterreport_cpp_tw_sentiment(SEXP xSEXP, SEXP posSEXP, SEXP negSEXP, SEXP pos_scoreSEXP, SEXP neg_scoreSEXP, SEXP neuSEXP, SEXP neu_scoreSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pos(posSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type neg(negSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type pos_score(pos_scoreSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type neg_score(neg_scoreSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type neu(neuSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type neu_score(neu_scoreSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_tw_sentiment(x, pos, neg, pos_score, neg_score, neu, neu_score, normalize));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_twitterreport_cpp_tw_gender", (DL_FUNC) &_twitterreport_cpp_tw_gender, 3},
    {"_twitterreport_cpp_jaccard_coef", (DL_FUNC) &_twitterreport_cpp_jaccard_coef, 3},
    {"_twitterreport_cpp_char_list_as_df", (DL_FUNC) &_twitterreport_cpp_char_list_as_df, 1},
    {"_twitterreport_cpp_tw_sentiment", (DL_FUNC) &_twitterreport_cpp_tw_sentiment, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_twitterreport(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
