# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_tw_gender <- function(x, male, female) {
    .Call(`_twitterreport_cpp_tw_gender`, x, male, female)
}

cpp_jaccard_coef <- function(wrds_id, wrds_grp, dist = FALSE) {
    .Call(`_twitterreport_cpp_jaccard_coef`, wrds_id, wrds_grp, dist)
}

cpp_char_list_as_df <- function(X) {
    .Call(`_twitterreport_cpp_char_list_as_df`, X)
}

cpp_tw_sentiment <- function(x, pos, neg = as.character( c()), pos_score = as.numeric( c()), neg_score = as.numeric( c()), neu = as.character( c()), neu_score = as.numeric( c()), normalize = TRUE) {
    .Call(`_twitterreport_cpp_tw_sentiment`, x, pos, neg, pos_score, neg_score, neu, neu_score, normalize)
}

